sweat2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tracker.urls', namespace='tracker')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

tracker/urls.py
from django.conf.urls import url
from django.contrib.auth.forms import AuthenticationForm

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.urlpatterns import format_suffix_patterns


# from .forms import OnsAuthForm
from .views import (Index, Home, SessionCreate, SessionDetail, SessionExercise, ExerciseNameCreate, ExerciseNameDetail,
                    ExerciseNameList, SessionExerciseCreate, SessionExerciseUpdate, ExerciseUserDetail)

from . import api

urlpatterns = [
    # ------------------------ API------------------------------------------
    url(r'^snippets/$', api.SnippetList.as_view()),
    url(r'^snippets/(?P<pk>[0-9]+)/$', api.SnippetDetail.as_view()),



    # ------------------------ Normal ---------------------------------------------
    url(r'^logout/$', LogoutView.as_view(template_name='tracker/logout.html', redirect_field_name='tracker:home'), name='logout'),
    url(r'^login/$', LoginView.as_view(template_name='tracker/login.html', ), name='login'),
    url(r'^home/$', Home.as_view(), name='home'),

    # Session URLs
    # Anything within a (?P<label>[]) is sent as an kwarg to the view
    url(r'session/(?P<pk>\d+)/$', SessionDetail.as_view(), name='session'),
    url(r'session/add/$', SessionCreate.as_view(), name='session-add'),
    # Exercise page for specific session - Mash between a detail view and update view
    url(r'session/(?P<pk>\d+)/(?P<exercise_name>[-\w]+)/$', SessionExercise.as_view(),
        name='session_exercise'),
    url(r'session/(?P<pk>\d+)/exercise/(?P<exercise_name>[-\w]+)/(?P<ex_id>\d+)/$', SessionExerciseUpdate.as_view(),
        name='session_exercise_update'),
    # Add new instance of an exercise to a session - redirects to specific page
    url(r'session/(?P<pk>\d+)/(?P<exercise_name>[-\w]+)/add/$', SessionExerciseCreate.as_view(),
        name='session_exercise_create'),

    # Exercise URLs
    url(r'^exercises/$', ExerciseNameList.as_view(), name='exercise_name_list'),
    url(r'exercise_name/add/$', ExerciseNameCreate.as_view(), name='exercise_name_create'),
    # General information about each exercise
    url(r'exercise_name/(?P<slug>[-\w]+)/$', ExerciseNameDetail.as_view(), name='exercise_name'),
    # This url needs to come at the bottom - Shows exercises of one type of exercise name for each user
    url(r'user/(?P<exercise_name>[-\w]+)/$', ExerciseUserDetail.as_view(), name='exercise_user_detail'),

    url(r'^about/$', Index.as_view()),
    url(r'^foundation/$', LoginView.as_view(template_name='tracker/foundation.html')),
    url(r'^/$', Index.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

tracker/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.functions.base import Concat
from django.urls import reverse

# from .managers import ExerciseManager


# Create your models here.
class Timestamp(models.Model):
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        abstract = True


class Session(Timestamp):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return str(self.timestamp.strftime('%a %d %B %Y - %H:%M'))

    def get_absolute_url(self):
        return reverse('tracker:session', kwargs={'pk': self.pk})


class Workout(models.Model):
    workout = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.workout


class MuscleGroup(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ExerciseName(models.Model):
    exercise_name = models.CharField(max_length=60, blank=False, null=False)
    slug = models.SlugField(unique=True)
    equipment_weight = models.IntegerField(default=0, blank=False, null=False)
    weight_multiplier = models.IntegerField(default=1, blank=False, null=False)

    muscle_group = models.ForeignKey(MuscleGroup, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.exercise_name

    def get_absolute_url(self):
        return reverse('tracker:exercise_name', kwargs={'slug': self.slug})


class Reps(models.Model):
    reps = models.IntegerField()

    def __str__(self):
        return str(self.reps)

    class Meta:
        ordering = ['reps']


class Weight(models.Model):
    weight = models.FloatField()

    def __str__(self):
        return str(self.weight)

    class Meta:
        ordering = ['weight']


class Sets(models.Model):
    sets = models.IntegerField()

    def __str__(self):
        return str(self.sets)

    class Meta:
        ordering = ['sets']


class ExerciseManager(models.Manager):
    def get_bench_press(self, user, *args, **kwargs):
        bench_press_obj = ExerciseName.objects.get(slug='bench-press')
        qs = Exercise.objects.filter(exercise=bench_press_obj, user=user)
        return qs

    def get_exercises(self, exercise_name, user, *args, **kwargs):
        exercise_name_obj = ExerciseName.objects.get(slug=exercise_name)
        qs = Exercise.objects.filter(exercise_name_obj)
        return qs

    def get_max_bp(self, user, *args, **kwargs):
        bench_press_obj = ExerciseName.objects.get(slug='bench-press')
        qs = Exercise.objects.filter(exercise=bench_press_obj, user=user)
        qs.annotate(date_weight=Concat('timestamp'))
        return qs

# Annotate each obj with date + weight, order on that, then get the first of each date which should be the largest
# weight as they all have the same date


class Exercise(Timestamp):
    user = models.ForeignKey(User)
    session = models.ForeignKey(Session)
    exercise = models.ForeignKey(ExerciseName)
    weight = models.ForeignKey(Weight, on_delete=models.CASCADE, blank=True, null=True)
    reps = models.ForeignKey(Reps, on_delete=models.CASCADE, blank=True, null=True)
    sets = models.ForeignKey(Sets, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.exercise) + ' ' + str(self.weight) + ' x' + str(self.reps) + ' x' + str(self.sets)

    def get_absolute_url(self):
        return reverse('tracker:session_exercise', kwargs={'pk': self.session_id, 'exercise_name': self.exercise.slug})

    def get_volume(self):
        total_weight = (self.weight.weight * self.exercise.weight_multiplier) + self.exercise.equipment_weight
        total_volume = total_weight * self.reps.reps * self.sets.sets
        return total_volume

    objects = models.Manager()
    exercise_manager = ExerciseManager()

tracker/forms.py
import unicodedata

from django.contrib.auth.forms import AuthenticationForm
from django import forms


# class OnsAuthForm(AuthenticationForm):
#     # username = forms.CharField(widget=forms.TextInput(template_name='/widgets/ons-input.html'))

tracker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F, FloatField, ExpressionWrapper, Sum, Max
from django.urls import reverse
from django.views.generic import FormView, RedirectView, TemplateView, ListView, CreateView, DetailView, RedirectView, UpdateView
from django.views.generic.base import ContextMixin

from .models import Session, Exercise, ExerciseName, Reps, Sets, Weight


# Custom Mixins
class CustomLoginRequiredMixin(LoginRequiredMixin):
    login_url = 'tracker:login'


class CustomContextMixin(object):
    def get_context_data(self, **kwargs):
        context = super(CustomContextMixin, self).get_context_data(**kwargs)

        session_obj = Session.objects.get(id=self.kwargs['pk'])
        context['session'] = session_obj
        context['exercises'] = Exercise.objects.filter(session=session_obj)

        context['exercise_names'] = ExerciseName.objects.all().order_by('muscle_group')

        if 'exercise_name' in self.kwargs:
            exercise_name_obj = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
            context['exercise_name'] = exercise_name_obj

        print('In mixin')
        print(self.kwargs)
        return context


# Create your views here.
class Index(TemplateView):
    template_name = 'tracker/about.html'


class Home(CustomLoginRequiredMixin, ListView):
    template_name = 'tracker/home.html'
    model = Session
    context_object_name = 'sessions'

    def get_queryset(self):
        print(Exercise.exercise_manager.get_bench_press(user=self.request.user).count())
        return Session.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        # Add more data to be sent to the template
        # Call the base implementation first to get a context
        context = super(Home, self).get_context_data(**kwargs)
        print(get_session_volume_data(self.request))
        context['session_volume_chart'] = get_session_volume_data(self.request)
        return context


def get_session_volume_data(request):
    sessions = Session.objects.filter(user=request.user)
    session_volume_chart = []
    for session in sessions:
        exercises = session.exercise_set.all()
        volume = 0
        for exercise in exercises:
            volume += exercise.get_volume()
        session_volume_chart.append([exercise.timestamp.strftime('%Y-%m-%d'), volume])

    # apply get total volume to each exercise - create own query expression
    # sum each total volume - aggregate
    print(session_volume_chart)
    return session_volume_chart


class SessionDetail(CustomContextMixin, CustomLoginRequiredMixin, DetailView):
    # eg session/1/
    template_name = 'tracker/session.html'
    model = Session
    context_object_name = 'session'

    def get_context_data(self, **kwargs):
        # Add more data to be sent to the template
        # Call the base implementation first to get a context
        context = super(SessionDetail, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the exercises of this session
        # context['exercises'] = Exercise.objects.filter(session_id=self.kwargs['pk'])
        # context['exercise_names'] = ExerciseName.objects.all()

        # Get stats from the session
        # Number of exercises
        session_obj = Session.objects.get(id=self.kwargs['pk'])
        exercise_qs = Exercise.objects.filter(session=session_obj)
        context['exercise_number'] = exercise_qs.distinct('exercise').count()

        # Total weight lifted
        weight_qs = exercise_qs.annotate(
            total_weight=ExpressionWrapper(F('weight__weight') * F('reps__reps') * F('sets__sets'),
                                           output_field=FloatField()))
        for i in weight_qs:
            print(i, i.total_weight)

        print(weight_qs.aggregate(Sum('total_weight')))
        context['total_weight_lifted'] = weight_qs.aggregate(Sum('total_weight'))
        return context


class SessionCreate(CustomLoginRequiredMixin, RedirectView):
    # /session/add - creates a new Session object and redirects to that page

    def get_redirect_url(self, *args, **kwargs):
        # Create new session object
        new_session = Session.objects.create(user=self.request.user)
        url = reverse('tracker:session', kwargs={'pk': new_session.id})
        return url


class SessionExercise(CustomLoginRequiredMixin, ListView):
    # session/(?P<pk>\d+)/exercise/(?P<exercise_name>\w+)/
    # session/1/exercise/dips/
    template_name = 'tracker/session_exercise.html'
    model = Exercise
    context_object_name = 'exercises'

    def get_queryset(self):
        exercise_name = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        qs = Exercise.objects.filter(session=self.kwargs['pk'], exercise=exercise_name)
        return qs

    def get_context_data(self, **kwargs):
        # Add more data to be sent to the template
        # Call the base implementation first to get a context
        context = super(SessionExercise, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the exercises of this session
        session_obj = Session.objects.get(id=self.kwargs['pk'])
        context['session'] = session_obj
        exercise_name_obj = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        context['exercise_name'] = exercise_name_obj

        return context


class SessionExerciseCreate(CustomLoginRequiredMixin, CreateView):
    # session/(?P<pk>\d+)/(?P<exercise_name>[-\w]+)/add
    template_name = 'tracker/session_exercise_create.html'
    fields = ['weight', 'reps', 'sets', 'comment']
    model = Exercise

    def form_valid(self, form):
        exercise_name = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        form.instance.exercise = exercise_name

        session = Session.objects.get(id=self.kwargs['pk'])
        form.instance.session_id = session.id

        # TODO Probably not the best way to get the user, through the session object, but it works for now.
        user = User.objects.get(id=session.user_id)
        form.instance.user = user
        return super(SessionExerciseCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        # Add more data to be sent to the template
        # Call the base implementation first to get a context
        context = super(SessionExerciseCreate, self).get_context_data(**kwargs)

        session = Session.objects.get(id=self.kwargs['pk'])
        context['session'] = session

        exercise_name = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        context['exercise_name'] = exercise_name

        user = User.objects.get(id=session.user_id)
        exercise_qs = Exercise.objects.filter(user=user, exercise=exercise_name)
        context['exercise_qs'] = exercise_qs
        return context

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super(SessionExerciseCreate, self).get_initial()
        exercise_name_obj = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        one_rep = Reps.objects.get(reps=1)
        one_set = Sets.objects.get(sets=1)

        initial['reps'] = one_rep
        initial['sets'] = one_set

        # Fill weight with same weight as previous exercise
        # TODO need to limit this for just current user, if none => blank
        try:
            last_exercise = Exercise.objects.filter(user=self.request.user, exercise=exercise_name_obj).latest('timestamp')
            initial['weight'] = last_exercise.weight
        except ObjectDoesNotExist:
            pass

        return initial


class SessionExerciseUpdate(CustomLoginRequiredMixin, UpdateView):
    # 'session/(?P<pk>\d+)/exercise/(?P<exercise_name>[-\w]+)/(?P<ex_id>\d+)/$'
    template_name = 'tracker/session_exercise_update.html'
    model = Exercise
    fields = ['weight', 'reps', 'sets', 'comment']
    pk_url_kwarg = 'ex_id'

    def get_context_data(self, **kwargs):
        context = super(SessionExerciseUpdate, self).get_context_data(**kwargs)
        session_id = self.kwargs['pk']
        context['session'] = Session.objects.get(id=session_id)

        exercise_name = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        context['exercise_name'] = exercise_name

        exercise_qs = Exercise.objects.filter(session_id=session_id, exercise=exercise_name)
        context['exercise_qs'] = exercise_qs

        ex = Exercise.objects.get(id=self.kwargs['ex_id'])
        print(ex.get_volume())
        return context


class ExerciseNameList(CustomLoginRequiredMixin, ListView):
    template_name = 'tracker/exercise_name_list.html'
    model = ExerciseName
    context_object_name = 'exercises'


# TODO probs need to change this to model exercise and li
class ExerciseNameDetail(CustomLoginRequiredMixin, DetailView):
    # 'exercise_name/(?P<slug>[-\w]+)
    # General information about each exercise
    template_name='tracker/exercise_name.html'
    model = ExerciseName


class ExerciseNameCreate(CustomLoginRequiredMixin, CreateView):
    # exercise_name/add/
    template_name = 'tracker/exercise_name_create.html'
    model = ExerciseName
    fields = ['exercise_name']


class ExerciseUserDetail(CustomLoginRequiredMixin, ListView):
    # '(?P<exercise_name>[-\w]+)/$'
    # Shows exercises of one type of exercise name for each user
    template_name = 'tracker/exercise_user_detail.html'
    model = Exercise
    context_object_name = 'exercises'

    def get_queryset(self):
        exercise_obj = ExerciseName.objects.get(slug=self.kwargs['exercise_name'])
        return Exercise.objects.filter(user=self.request.user, exercise=exercise_obj)

    def get_context_data(self, **kwargs):
        context = super(ExerciseUserDetail, self).get_context_data(**kwargs)

tracker/templates/tracker/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% block extrahead %}{% endblock extrahead %}
    {% include 'tracker/base_css.html' %}


</head>
<body>
{% include 'tracker/navbar.html' %}

<!--Impromptu Navbar-->

{% block content %}
{% endblock %}


{% include 'tracker/base_js.html' %}

{% block extra_js %}
{% endblock %}
</body>
</html>

tracker/templates/tracker/base_css.html
{% load staticfiles %}

<!--Contains various CSS files for loading from base.html-->

<!--Bootstrap CSS-->
<link href="{% static 'tracker/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'tracker/css/custom.css' %}" rel="stylesheet">


<!--Fontawesome-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<!--<link rel="stylesheet" href="{% static 'tracker/css/font-awesome.min.css' %}">-->

<!--Custom css styles to override certain class styles-->

tracker/templates/tracker/base_js.html
{% load staticfiles %}

<!--Contains and loads all the js files in base.html-->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'tracker/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'tracker/js/popper.min.js' %}"></script>
<script src="{% static 'tracker/js/bootstrap.min.js' %}"></script>
<script src="{% static 'tracker/js/moment.js' %}"></script>
<script src="{% static 'tracker/js/chart.min.js' %}"></script>

tracker/templates/tracker/exercise_name.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block title %}{{object}}{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}
<div class="container"/>
<h1>{{ object }}</h1>
<p>General information about {{ object }}</p>

</div>
{% endblock %}

tracker/templates/tracker/exercise_name_create.html
{% extends "tracker/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block title %}Create new exercise{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}
<div class="container"/>
<form class="form" method="post" action="{% url 'tracker:exercise_name_create' %}">
    <h2 class="form-signin-heading">Create new exercise</h2>
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
    <input type="hidden" name="next" value="{{ next }}"/>
</form>

</div>
{% endblock %}

tracker/templates/tracker/exercise_name_list.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block title %}Exercise{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}
<div class="container"/>
<h1>Exercise </h1>
{% for exercise in exercises %}
<a class="btn btn-lg btn-primary btn-block" role="button" href="{% url 'tracker:exercise_user_detail' exercise_name=exercise.slug %}">{{ exercise }}</a>
{% endfor %}


</div>
{% endblock %}

tracker/templates/tracker/home.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block title %}Home{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}
<div class="container"/>
    <div class="row">
        <!--Session buttons-->
        <div class="col-md-6">
            <h1 class="text-center">{{request.user}}'s Sessions</h1>

        {% for session in sessions %}
        <a class="btn btn-lg btn-primary btn-block" role="button" href="{% url 'tracker:session' pk=session.id %}">{{ session }}</a>
        {% endfor %}

        <a class="btn btn-lg btn-primary btn-block btn-success" role="button" href="{% url 'tracker:session-add' %}">Start new session</a>
        </div>
        <!--Session volume chart-->
        <div class="col-md-6">
            <canvas id="sessionVolumeChart" width="100" height="100"></canvas>
        </div>




    </div>


</div>
{% endblock %}


{% block extra_js %}
<script>
  var volume_data={
        labels: [{% for session in session_volume_chart %}moment('{{session.0}}'),{% endfor %}],
        datasets: [{
            label: 'Volume per Session',
            data: [{% for volume in session_volume_chart %}{{volume.1}},{% endfor %}],
            borderColor:'rgb(244, 66, 101)',
            backgroundColor: 'rgba(255, 201, 211, 0.1)',
        }]
    };
</script>
<script src="{% static 'tracker/js/home.js' %}"></script>
{% endblock %}

tracker/templates/tracker/logout.html
<h1>logged out</h1>

tracker/templates/tracker/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'tracker:home' %}">Sweat</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:exercise_name_list' %}">Exercises</a>
            </li>
        </ul>
        <!--User and Logout on right hand side of navbar -->
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mt-2 mt-md-0">
            <li class="nav-item">
                <a class="nav-link" href="#">{{ request.user }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:logout' %}">Logout</a>
            </li>
        </ul>
        {% endif %}
        <!--<form class="form-inline mt-2 mt-md-0">-->
            <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--</form>-->
    </div>
</nav>

<!--<nav class="navbar navbar-dark bg-dark fixed-top">-->
  <!--<form class="form-inline">-->
    <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
    <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
  <!--</form>-->
<!--</nav>-->

tracker/templates/tracker/session.html
{% extends "tracker/base.html" %}
{% load staticfiles %}

{% block title %}Session{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}

<div class="container">
    <h1>Session Detail View</h1>
    <p>{{ session }}</p>

    <div class="list-group">
        <h1>Exercises</h1>
        {% for exercise in exercises %}
        <a href="{% url 'tracker:session_exercise_update' pk=session.id exercise_name=exercise.exercise.slug ex_id=exercise.id %}"
           class="list-group-item list-group-item-action">{{ exercise }}</a>
        {% endfor %}
    </div>

    <!--Add new exercise-->
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
            Add new exercise
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for exercise_name in exercise_names %}
            <a class="dropdown-item"
               href="{% url 'tracker:session_exercise_create' pk=session.id exercise_name=exercise_name.slug %}">{{ exercise_name }}</a>
            {% endfor %}
        </div>
    </div>
    <br>
    <!--Add new ExerciseName-->
    <a class="btn btn-secondary" role="button" href="{% url 'tracker:exercise_name_create' %}">Add new exercise type</a>

    <!--Session Stats-->
    <div id="session-stats">
        <div class="card-deck">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Number of Exercises</h4>
                    <p class="card-text display-1 text-center">{{exercise_number}}</p>

                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Total Weight Lifted</h4>
                    <p class="card-text text-center">{{total_weight_lifted.total_weight__sum}}</p>

                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Card title</h4>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional
                        content. This card has even longer content than the first to show that equal height action.</p>
                    <p class="card-text">
                        <small class="text-muted">Last updated 3 mins ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

tracker/templates/tracker/session_exercise_update.html
{% extends "tracker/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block title %}Update session exercise{% endblock title %}

<!-- Custom styles for this template -->
{% block extrahead %}
{% endblock extrahead %}

{% block content %}
<div class="container"/>
<a href="{% url 'tracker:session' pk=session.id %}"><h3>{{ session }}</h3></a>
<h3>{{ exercise_name }} <i class="fa fa-info-circle" aria-hidden="true"></i></h3>
<form class="form" method="post" action="">
    <h2 class="form-signin-heading">Update {{ exercise_name }} instance <a class="btn btn-primary" href="{% url 'tracker:session_exercise_create' pk=session.id exercise_name=exercise_name.slug %}" role="button">Add New</a></h2>
    {% csrf_token %}
    {{ form|crispy }}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
    <input type="hidden" name="next" value="{{ next }}"/>
</form>

<!--A group list of past same exercises -->

<ul class="list-group">
    {% for exercise in exercise_qs %}
    <li class="list-group-item">{{exercise}}</li>
    {% endfor %}
</ul>

</div>
{% endblock %}